// ============================================
// DAX Measures — LA MECHKY Leadership Dashboard
// ============================================
//
// Create these in the semantic model editor (Power BI web):
//   Open data model > Editing mode > New measure > Paste DAX code
//
// All measures reference the 'AnnualSummary' table.
// Requires relationship: AnnualSummary[fullName] → EmployeeConfig[fullName] (Many-to-One)


// ════════════════════════════════════════════
// PAGE 1: COMPANY HEALTH OVERVIEW
// ════════════════════════════════════════════

// ── Core KPIs ──────────────────────────────

Billable Efficiency % =
    VAR BillableHrs = SUM('AnnualSummary'[togglBillableHours])
    VAR TotalToggl = SUM('AnnualSummary'[togglTotalHours])
    RETURN
        IF(TotalToggl > 0,
            DIVIDE(BillableHrs, TotalToggl, 0) * 100,
            BLANK()
        )

// Filtered version: only employees flagged as billable roles
// Requires relationship: AnnualSummary[fullName] → EmployeeConfig[fullName]
Billable Efficiency % (Billable Roles) =
    VAR BillableHrs =
        CALCULATE(
            SUM('AnnualSummary'[togglBillableHours]),
            'EmployeeConfig'[isBillableRole] = TRUE()
        )
    VAR TotalToggl =
        CALCULATE(
            SUM('AnnualSummary'[togglTotalHours]),
            'EmployeeConfig'[isBillableRole] = TRUE()
        )
    RETURN
        IF(TotalToggl > 0,
            DIVIDE(BillableHrs, TotalToggl, 0) * 100,
            BLANK()
        )

Total Scheduled Hours = SUM('AnnualSummary'[scheduledHours])

Total Worked Hours (Absence) = SUM('AnnualSummary'[workedHours])

Total Toggl Hours = SUM('AnnualSummary'[togglTotalHours])

Total Billable Hours = SUM('AnnualSummary'[togglBillableHours])

Total Non-Billable Hours = SUM('AnnualSummary'[togglNonBillableHours])

Total Overtime Hours = SUM('AnnualSummary'[overtimeHours])

Total Absence Days = SUM('AnnualSummary'[absenceDays])

Total Holidays = SUM('AnnualSummary'[holidayCount])

Active Headcount =
    DISTINCTCOUNT('AnnualSummary'[fullName])


// ── Trend Indicators ───────────────────────

// Compare current month to previous month
Efficiency Change MoM =
    VAR CurrentSort = MAX('AnnualSummary'[monthSort])
    VAR PrevSort = CurrentSort - 1
    VAR CurrentEff =
        CALCULATE([Billable Efficiency %],
            'AnnualSummary'[monthSort] = CurrentSort)
    VAR PrevEff =
        CALCULATE([Billable Efficiency %],
            'AnnualSummary'[monthSort] = PrevSort)
    RETURN
        IF(NOT ISBLANK(PrevEff), CurrentEff - PrevEff, BLANK())


// ════════════════════════════════════════════
// PAGE 2: EXPECTATION VS REALITY
// ════════════════════════════════════════════

// Target billable hours from EmployeeConfig
// (requires targetBillableHoursPerDay to be filled in for each employee)
// Requires relationship: AnnualSummary[fullName] → EmployeeConfig[fullName]
Target Billable Hours =
    VAR DaysInMonth = 22  // approximate; override with actual if needed
    RETURN
        SUMX(
            VALUES('AnnualSummary'[fullName]),
            LOOKUPVALUE(
                'EmployeeConfig'[targetBillableHoursPerDay],
                'EmployeeConfig'[fullName], 'AnnualSummary'[fullName],
                0
            ) * DaysInMonth
        )

// Gap: actual vs target (positive = ahead, negative = behind)
Billable Hours Gap =
    [Total Billable Hours] - [Target Billable Hours]

// YoY comparison: same month last year
Billable Hours Same Month Last Year =
    VAR CurrentYear = MAX('AnnualSummary'[year])
    VAR CurrentMonth = MAX('AnnualSummary'[month])
    RETURN
        CALCULATE(
            SUM('AnnualSummary'[togglBillableHours]),
            'AnnualSummary'[year] = CurrentYear - 1,
            'AnnualSummary'[month] = CurrentMonth,
            ALL('AnnualSummary'[year]),
            ALL('AnnualSummary'[monthSort]),
            ALL('AnnualSummary'[monthLabel]),
            ALL('AnnualSummary'[monthDate])
        )

YoY Billable Change % =
    VAR LastYear = [Billable Hours Same Month Last Year]
    VAR ThisYear = [Total Billable Hours]
    RETURN
        IF(LastYear > 0,
            DIVIDE(ThisYear - LastYear, LastYear, 0) * 100,
            BLANK()
        )


// ════════════════════════════════════════════
// PAGE 3: DATA QUALITY & TRACKING COMPLIANCE
// ════════════════════════════════════════════

// How much of scheduled time is tracked in Toggl?
Toggl Coverage % =
    DIVIDE(
        SUM('AnnualSummary'[togglTotalHours]),
        SUM('AnnualSummary'[scheduledHours]),
        0
    ) * 100

// Gap between what Absence expects and what Toggl records
Tracking Gap Hours =
    SUM('AnnualSummary'[scheduledHours]) - SUM('AnnualSummary'[togglTotalHours])

// Absence.io worked hours vs Toggl total (should be close for accurate trackers)
Absence vs Toggl Difference =
    SUM('AnnualSummary'[workedHours]) - SUM('AnnualSummary'[togglTotalHours])


// ════════════════════════════════════════════
// PAGE 4: EMPLOYEE DEEP-DIVE
// ════════════════════════════════════════════

// Per-employee efficiency (use with fullName slicer)
Employee Billable Ratio % =
    VAR Billable = SUM('AnnualSummary'[togglBillableHours])
    VAR Total = SUM('AnnualSummary'[togglTotalHours])
    RETURN
        IF(Total > 0, DIVIDE(Billable, Total, 0) * 100, BLANK())

// Overtime indicator
Has Overtime =
    IF(SUM('AnnualSummary'[overtimeHours]) > 0, "Yes", "No")

// Average monthly hours
Avg Monthly Scheduled Hours =
    AVERAGEX(
        VALUES('AnnualSummary'[monthSort]),
        CALCULATE(SUM('AnnualSummary'[scheduledHours]))
    )

Avg Monthly Toggl Hours =
    AVERAGEX(
        VALUES('AnnualSummary'[monthSort]),
        CALCULATE(SUM('AnnualSummary'[togglTotalHours]))
    )


// ════════════════════════════════════════════
// PAGE 5: DEPARTMENT / TEAM COMPARISON
// ════════════════════════════════════════════

// Department-level efficiency
Dept Billable Efficiency % =
    VAR BillableHrs = SUM('AnnualSummary'[togglBillableHours])
    VAR TotalToggl = SUM('AnnualSummary'[togglTotalHours])
    RETURN
        IF(TotalToggl > 0, DIVIDE(BillableHrs, TotalToggl, 0) * 100, BLANK())

// Department overtime rate
Dept Overtime Rate % =
    DIVIDE(
        SUM('AnnualSummary'[overtimeHours]),
        SUM('AnnualSummary'[scheduledHours]),
        0
    ) * 100

// Department absence rate
Dept Absence Rate =
    DIVIDE(
        SUM('AnnualSummary'[absenceDays]),
        DISTINCTCOUNT('AnnualSummary'[fullName]),
        0
    )

// FTE count (approximate: scheduled hours / 160 per month)
Approx FTE =
    DIVIDE(
        SUM('AnnualSummary'[scheduledHours]),
        160,
        0
    )


// ════════════════════════════════════════════
// UTILITY / FORMATTING
// ════════════════════════════════════════════

// Conditional formatting: efficiency color
Efficiency Color =
    VAR Eff = [Billable Efficiency %]
    RETURN
        SWITCH(
            TRUE(),
            Eff >= 70, "#2ECC71",   // Green: at target
            Eff >= 55, "#F39C12",   // Orange: getting close
            Eff > 0,   "#E74C3C",   // Red: below target
            "#CCCCCC"               // Grey: no data
        )

// Target reference line value (70%)
Target Efficiency = 70

// Last data refresh timestamp
Last Toggl Refresh =
    MAX('AnnualSummary'[togglLastRefresh])


// ════════════════════════════════════════════
// PAGES 6-8: PROJECT & CLIENT ANALYSIS
// ════════════════════════════════════════════
// These measures reference the 'ProjectBreakdown' table.
// Requires: ProjectBreakdown query loaded + relationship:
//   ProjectBreakdown[fullName] → EmployeeConfig[fullName] (Many-to-One)
//
// Create these by selecting the ProjectBreakdown table in the Data pane,
// then Ribbon > New measure > paste each measure.


// ── Core Aggregates ──────────────────────────

Proj Total Hours = SUM('ProjectBreakdown'[totalHours])

Proj Billable Hours = SUM('ProjectBreakdown'[billableHours])

Proj Non-Billable Hours = SUM('ProjectBreakdown'[nonBillableHours])

Proj Billable Ratio % =
    VAR BillableHrs = SUM('ProjectBreakdown'[billableHours])
    VAR TotalHrs = SUM('ProjectBreakdown'[totalHours])
    RETURN
        IF(TotalHrs > 0,
            DIVIDE(BillableHrs, TotalHrs, 0) * 100,
            BLANK()
        )


// ── Proportional Analysis ────────────────────

// What % of total company hours does this project/client represent?
Proj % Of Company Hours =
    VAR ProjectHours = SUM('ProjectBreakdown'[totalHours])
    VAR AllHours =
        CALCULATE(
            SUM('ProjectBreakdown'[totalHours]),
            ALL('ProjectBreakdown'[projectName]),
            ALL('ProjectBreakdown'[clientName])
        )
    RETURN
        IF(AllHours > 0,
            DIVIDE(ProjectHours, AllHours, 0) * 100,
            BLANK()
        )

// What % of all billable hours does this client contribute?
Client % Of Billable Hours =
    VAR ClientBillable = SUM('ProjectBreakdown'[billableHours])
    VAR AllBillable =
        CALCULATE(
            SUM('ProjectBreakdown'[billableHours]),
            ALL('ProjectBreakdown'[clientName])
        )
    RETURN
        IF(AllBillable > 0,
            DIVIDE(ClientBillable, AllBillable, 0) * 100,
            BLANK()
        )


// ── Counting ─────────────────────────────────

Active Project Count =
    DISTINCTCOUNT('ProjectBreakdown'[projectName])

Active Client Count =
    DISTINCTCOUNT('ProjectBreakdown'[clientName])


// ── Non-Billable Analysis ────────────────────

// What % of all non-billable hours does this project/category represent?
Non-Billable % Of Category =
    VAR CategoryNonBillable = SUM('ProjectBreakdown'[nonBillableHours])
    VAR TotalNonBillable =
        CALCULATE(
            SUM('ProjectBreakdown'[nonBillableHours]),
            ALL('ProjectBreakdown'[projectName]),
            ALL('ProjectBreakdown'[clientName])
        )
    RETURN
        IF(TotalNonBillable > 0,
            DIVIDE(CategoryNonBillable, TotalNonBillable, 0) * 100,
            BLANK()
        )

// Average hours per month for this project/client
Avg Monthly Project Hours =
    AVERAGEX(
        VALUES('ProjectBreakdown'[monthSort]),
        CALCULATE(SUM('ProjectBreakdown'[totalHours]))
    )

// Month-over-month change in non-billable hours (%)
Non-Billable MoM Change % =
    VAR CurrentSort = MAX('ProjectBreakdown'[monthSort])
    VAR PrevSort = CurrentSort - 1
    VAR CurrentHrs =
        CALCULATE(
            SUM('ProjectBreakdown'[nonBillableHours]),
            'ProjectBreakdown'[monthSort] = CurrentSort
        )
    VAR PrevHrs =
        CALCULATE(
            SUM('ProjectBreakdown'[nonBillableHours]),
            'ProjectBreakdown'[monthSort] = PrevSort
        )
    RETURN
        IF(NOT ISBLANK(PrevHrs) && PrevHrs > 0,
            DIVIDE(CurrentHrs - PrevHrs, PrevHrs, 0) * 100,
            BLANK()
        )


// ── Employee-Project Analysis ────────────────

// What % of a client's billable hours come from this employee?
// (Use with client slicer to spot single-person dependencies)
Employee % Of Client =
    VAR EmployeeClientHrs = SUM('ProjectBreakdown'[billableHours])
    VAR AllClientHrs =
        CALCULATE(
            SUM('ProjectBreakdown'[billableHours]),
            ALL('ProjectBreakdown'[fullName])
        )
    RETURN
        IF(AllClientHrs > 0,
            DIVIDE(EmployeeClientHrs, AllClientHrs, 0) * 100,
            BLANK()
        )

// How many distinct projects does this employee work on?
Employee Project Count =
    DISTINCTCOUNT('ProjectBreakdown'[projectName])


// ── Trend ────────────────────────────────────

// Month-over-month change in total hours (%)
Proj Hours MoM Change =
    VAR CurrentSort = MAX('ProjectBreakdown'[monthSort])
    VAR PrevSort = CurrentSort - 1
    VAR CurrentHrs =
        CALCULATE(
            SUM('ProjectBreakdown'[totalHours]),
            'ProjectBreakdown'[monthSort] = CurrentSort
        )
    VAR PrevHrs =
        CALCULATE(
            SUM('ProjectBreakdown'[totalHours]),
            'ProjectBreakdown'[monthSort] = PrevSort
        )
    RETURN
        IF(NOT ISBLANK(PrevHrs) && PrevHrs > 0,
            DIVIDE(CurrentHrs - PrevHrs, PrevHrs, 0) * 100,
            BLANK()
        )


// ── Conditional Formatting ───────────────────

// Color for project billable ratio (green ≥80, orange ≥50, red <50)
Proj Billable Color =
    VAR Ratio = [Proj Billable Ratio %]
    RETURN
        SWITCH(
            TRUE(),
            Ratio >= 80, "#2ECC71",
            Ratio >= 50, "#F39C12",
            Ratio > 0,  "#E74C3C",
            "#CCCCCC"
        )

// Color severity for non-billable hours (red ≥500h, orange ≥100h, green <100h)
Non-Billable Severity Color =
    VAR HoursVal = SUM('ProjectBreakdown'[nonBillableHours])
    RETURN
        SWITCH(
            TRUE(),
            HoursVal >= 500, "#E74C3C",
            HoursVal >= 100, "#F39C12",
            HoursVal > 0,   "#2ECC71",
            "#CCCCCC"
        )
